name: Sannnnnn

on:
  workflow_dispatch:
  

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 240
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/raposabrty/pcrdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Show Website
        run: cmd /c show.bat
        
      - name: Monitor System Usage and Send to Discord
        run: |
          $webhookUrl = "https://discord.com/api/webhooks/1356282679343054848/pUzE4WLfXSNW8_nehDoBzX0fR-uQMf7JolRQZb3hLxd6NGMjAh0RvXc7M6ZZX7z155tm"
          function Get-SystemStats {
              $cpuUsage = Get-WmiObject Win32_Processor | Select-Object -ExpandProperty LoadPercentage
              $memoryUsage = Get-WmiObject Win32_OperatingSystem | Select-Object -ExpandProperty FreePhysicalMemory
              $totalMemory = Get-WmiObject Win32_OperatingSystem | Select-Object -ExpandProperty TotalVisibleMemorySize
              $usedMemory = $totalMemory - $memoryUsage
              $usedMemoryMB = [math]::round($usedMemory / 1MB, 2)
              $totalMemoryMB = [math]::round($totalMemory / 1MB, 2)
              $cpuUsage = "CPU Usage: $cpuUsage%"
              $memoryUsage = "Memory Usage: $usedMemoryMB MB of $totalMemoryMB MB"
              return "$cpuUsage`n$memoryUsage"
          }
          
          # Send the stats to Discord every 5 minutes
          while ($true) {
              $systemStats = Get-SystemStats
              curl -H "Content-Type: application/json" -X POST -d '{"content": "'"$systemStats"'"}' $webhookUrl
              Start-Sleep -Seconds 300
          }
      - name: Time Counter
        run: cmd /c loop.bat

      - name: Auto Backup Github
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "SannBot"
          git add logs/
          git diff --cached --quiet || git commit -m "Auto-backup logs" && git push
